### pandas

> Pandas is a powerfull python library for manipulation array of data alanaysis of data

>Its a open source library

>fast(built on top of numpy),flexible(different resource),productive library

#### Inatall

In [2]:

! pip install pandas

Requirement already satisfied: pandas in .\.venv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in .\.venv\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd

In [4]:
pd.__version__

'3.0.3'

#### Series --One dimentional  array(data structure) with  lable

In [5]:
l1=[1,2,3,4,5]
type(l1)

list

In [6]:
s=pd.Series(l1,index=["a","b","c","d","e"],name="My series")

In [7]:
s['a']

np.int64(1)

In [8]:
type(s)

pandas.Series

>Note: Index in Series are imuutable(cant change)

In [9]:
s.index[0]

'a'

In [10]:
s.values

array([1, 2, 3, 4, 5])

In [11]:
# changung the index of pandas series

s.rename(index={'b':'y'},inplace=True)

In [12]:
s

a    1
y    2
c    3
d    4
e    5
Name: My series, dtype: int64

**DataFrame - Its a 2d array (just like tables)**

In [13]:
dict1={'name':['Prem','Ashok','Mayure','Vishal'],
     'age':[18,17,17,19],
      'marks':[85,88,87,92],
       'role':['Rider','Gamer','vloger','Editor'] }


df=pd.DataFrame(dict1)
type(df)

pandas.DataFrame

In [14]:
pd.DataFrame(dict1)

     name  age  marks    role
0    Prem   18     85   Rider
1   Ashok   17     88   Gamer
2  Mayure   17     87  vloger
3  Vishal   19     92  Editor

In [15]:
df=pd.DataFrame(dict1)
len(df)

4

In [16]:
df['name'].value_counts()

name
Prem      1
Ashok     1
Mayure    1
Vishal    1
Name: count, dtype: int64

In [17]:
df.columns

Index(['name', 'age', 'marks', 'role'], dtype='str')

In [18]:
df

     name  age  marks    role
0    Prem   18     85   Rider
1   Ashok   17     88   Gamer
2  Mayure   17     87  vloger
3  Vishal   19     92  Editor

In [19]:
df.head(4)

     name  age  marks    role
0    Prem   18     85   Rider
1   Ashok   17     88   Gamer
2  Mayure   17     87  vloger
3  Vishal   19     92  Editor

In [20]:
df.tail(4)

     name  age  marks    role
0    Prem   18     85   Rider
1   Ashok   17     88   Gamer
2  Mayure   17     87  vloger
3  Vishal   19     92  Editor

#### Basic operations

  Importing data set from different files
  
  Importing tabular dataset

In [21]:
stock_df=pd.read_csv(r"C:\Users\dell\Desktop\data analysis\data set\ETH_1h.csv")

In [22]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [23]:
stock_df.head()

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71

top 10 rows

In [24]:
stock_df.head(10)

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
5  2020-03-13 03-PM  ETHUSD  128.39  128.90  116.06  124.85  7378976.00
6  2020-03-13 02-PM  ETHUSD  134.03  137.90  125.50  128.39  3733916.89
7  2020-03-13 01-PM  ETHUSD  131.35  140.95  128.99  134.03  9582732.93
8  2020-03-13 12-PM  ETHUSD  128.93  134.60  126.95  131.35  3906590.52
9  2020-03-13 11-AM  ETHUSD  132.60  133.17  126.01  128.93  3311080.29

bottom 5 rows

In [25]:
stock_df.tail(5)

                   Date  Symbol    Open    High    Low   Close      Volume
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.0  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.0  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.0  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.0  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.1  275.01   679358.87

In [26]:
##  number of rows and dataframe
len(stock_df)

23674

Access colomn and dataframe

In [27]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [28]:
## accessing a colomn in a dataframe
stock_df['Open']

0        129.94
1        119.51
2        124.47
3        124.08
4        124.85
          ...
23669    265.74
23670    268.79
23671    274.83
23672    275.01
23673    279.98
Name: Open, Length: 23674, dtype: float64

In [29]:
## Accessing multiple in colomns in a dataframe
stock_df[['Open','Close','Volume']]

         Open   Close      Volume
0      129.94  128.71  1940673.93
1      119.51  129.94  7579741.09
2      124.47  119.51  4898735.81
3      124.08  124.47  2753450.92
4      124.85  124.08  4461424.71
...       ...     ...         ...
23669  265.74  272.57  1500282.55
23670  268.79  265.74  1702536.85
23671  274.83  268.79  3010787.99
23672  275.01  274.83   824362.87
23673  279.98  275.01   679358.87

[23674 rows x 3 columns]

In [30]:
stock_df.index

RangeIndex(start=0, stop=23674, step=1)

In [31]:
stock_df.loc[23672]

Date      2017-07-01 12-PM
Symbol              ETHUSD
Open                275.01
High                275.01
Low                  271.0
Close               274.83
Volume           824362.87
Name: 23672, dtype: object

In [32]:
stock_df.head()

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71

In [ ]:
stock_df.iloc[1,3] #row index and column index

np.float64(132.02)

In [ ]:
stock_df.iloc[3,[2,4]] #multiple column index

Open    124.08
Low     121.63
Name: 3, dtype: float64

In [36]:
stock_df.iloc[2,2:6] # slicing of columns using iloc

Open     124.47
High     124.85
Low       115.5
Close    119.51
Name: 2, dtype: object

In [37]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [38]:
stock_df.iloc[1:6,2:6] #

     Open    High     Low   Close
1  119.51  132.02  117.10  129.94
2  124.47  124.85  115.50  119.51
3  124.08  127.42  121.63  124.47
4  124.85  129.51  120.17  124.08
5  128.39  128.90  116.06  124.85

filternig

In [41]:
stock_df['High'] >130

0         True
1         True
2        False
3        False
4        False
         ...
23669     True
23670     True
23671     True
23672     True
23673     True
Name: High, Length: 23674, dtype: bool

In [42]:
f1=stock_df

In [43]:
f1

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [45]:
f1=stock_df['High'] > 130

stock_gt_130.reset_index(drop=True,inplace=True)

NameError: name 'stock_gt_130' is not defined